version: '2'
services:
  web:
    build: web
    restart: always
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=bolt
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - PASSBOLT_SECURITY_SALT=salt
      - PASSBOLT_SECURITY_SEED=1234
      - GNUPGHOME=/srv/keys/.gnupg
      - SMTP_HOST=mail.com
      - SMTP_PORT=537
      - SMTP_USER=user
      - SMTP_PASSWORD=pass
      - SMTP_FROM='contact@passbolt.com'
      - SMTP_FROM_NAME='Passbolt'
    links:
      - db
      - cache
    volumes:
      - keys:/srv/keys
  nginx:
    build: nginx
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    links:
      - web
    volumes:
      - letsencrypt-conf:/etc/letsencrypt
      - letsencrypt-data:/var/www/letsencrypt
  db:
    image: mariadb:10
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=bolt
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql
  cache:
    image: memcached:1
    restart: always
volumes:
  keys: {}
  db: {}
  letsencrypt-conf: {}
  letsencrypt-data: {}
