version: '2'
services:
  passbolt:
    image: passbolt/passbolt
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PASS=P4ssb0lt
      - DB_USER=passbolt
      - DB_NAME=passbolt
    links:
      - db
    volumes:
      - ./scripts/wait-for-it.sh:/usr/bin/wait-for-it.sh
      - ./data/passbolt/gpg_keys:/var/www/passbolt/app/Config/gpg
      - ./data/passbolt/certificates:/etc/ssl/certs
      - ./data/passbolt/images:/var/www/passbolt/app/webroot/img/public/images
    command: ["/usr/bin/wait-for-it.sh", "db:3306", "-t", "0", "--", "/docker-entrypoint.sh"]
    ports:
      - 8080:80
      - 8443:443

  db:
    image: mariadb:10
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=passbolt
      - MYSQL_USER=passbolt
      - MYSQL_PASSWORD=P4ssb0lt
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./data/mysql:/var/lib/mysql
