version: '2'
services:
  letsencrypt:
    build: letsencrypt
    volumes:
      - letsencrypt-conf:/etc/letsencrypt
      - letsencrypt-data:/var/www/letsencrypt
    command: renew --webroot

volumes:
  letsencrypt-conf: {}
  letsencrypt-data: {}
